import "./globals.css";
import ConvexClientProvider from "@/ConvexClientProvider";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className="bg-white dark:bg-black">
        <ConvexClientProvider>{children}</ConvexClientProvider>
      </body>
    </html>
  );
}
