import { ThemeProvider } from "next-themes";
import "./globals.css";
import ConvexClientProvider from "@/ConvexClientProvider";
export const metadata = {
  title: "AI video generator",
  description: "Generated by by using AI",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className="">
        <ConvexClientProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
